# Copyright 2017, Juniper Networks Pvt Ltd.
# All rights reserved.
# inspired by https://gist.github.com/jeffbrl/9485d1e0052151d69450
# Runs any show command in Junos. Not elegant but highly effective. Does not works with pipe commands. 
# command example: ansible-playbook -i all.inv -e '{ "CMD": "show route" }' junos_route_table_check-2.yml
# Successfully ran on ansible version: ansible 2.4.2.0: ansible-galaxy list Juniper.junos,1.4.3
---
- name: Get Device Facts
  hosts: junos-ssh
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
- name: Run CLI commands
  hosts: junos-ssh
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    temp_dir: /var/tmp/deleteme/
  tasks:
    - name:          Create temp directory
      file:          path={{ temp_dir }} state=directory

    - name: create temporary filename
      shell:  mktemp "{{ temp_dir }}"/`date +"%Y%m%d.%H%M%S%3N"`"_{{ inventory_hostname }}".XXXXX
      register: temp_file
    - name: Running commands
      junos_cli:
        host={{ inventory_hostname }}
        cli={{CMD}}
        dest="{{ temp_file.stdout }}"
        format=text

    - name: print temp_file to stdout
      command: cat "{{ temp_file.stdout }}"
      register: foo
    - debug: msg="{{ foo.stdout_lines }}"

    - name:          clean up temp directory
      file:          path={{ temp_dir }} state=absent
