# Copyright 2017, Juniper Networks Pvt Ltd.
# All rights reserved.
# Removes the overlay config
# command example: ansible-playbook -i all.inv remove-overlay.yml
# Successfully ran on ansible version: ansible 2.4.2.0: ansible-galaxy list Juniper.junos,1.4.3
---
- name: Removes overlay configs from the devices
  hosts: junos-leaf
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Removing the overlay config from the devices
      junos_install_config:
        host: "{{ inventory_hostname }}"
        replace: no
        overwrite: no
        confirm: 5
        file: "removeoverlay/{{ inventory_hostname }}-ovr-config.set"
    - name: Committing the configuration
      junos_commit:
        host: "{{ inventory_hostname }}"
        comment: "commit confirmed"
